apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-worker
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: worker
      tier: backend
      name: redis-master-deployment-for-gke
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: worker
        tier: backend
        name: redis-master-deployment-for-gke
    spec:
      containers:
      - name: worker
        image: k8s.gcr.io/google_samples/gb-redisslave:v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 6379
