apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-worker
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      role: worker
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: worker
        tier: backend
    spec:
      containers:
      - name: worker
        image: gcr.io/google-samples/gb-redisslave:v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 6379
